export const getSuccessedTodo = "Get Todo List"
export const getLoadTodo = "Loading Todo List"
export const getErrorTodo = "Get Error List"
export const postSuccessTodo = "Post New Todo"
export const postErrTodo = "Post Error Todo"
export const deleteErrTodo = 'Delete Error Todo'
export const updateTodo = "Update A Todo"
export const updateErrTodo = "Update Error Todo"
export const checkedObjTodo = 'checked Todo'
export const checkedErrTodo = 'checked Todo'