export const getSuccessedTodo = "Get Todo List"
export const getLoadTodo = "Loading Todo List"
export const getErrorTodo = "Get Error List"
export const postSuccessTodo = "Post New Todo"
export const deletetodo = "Delete A Todo"